services:

  # The classic key-value store, a configuration based on the base Service class
  key-value-store:
    image: ghcr.io/project8/dragonfly:develop-dev
    depends_on:
      - rabbit-broker
    volumes:
      - ./services/key-value-store.yaml:/root/key-value-store.yaml
      - ./dripline_mesh.yaml:/root/.dripline_mesh.yaml
    environment:
      - DRIPLINE_USER=dripline
      - DRIPLINE_PASSWORD=dripline
    command: >
      bash -c "dl-serve -vv -c /root/key-value-store.yaml"
    networks:
      - mesh

  sensor-logger:
    image: ghcr.io/project8/dragonfly:develop-dev
    depends_on:
      - rabbit-broker
      - postgres
    volumes:
      - ./services/sensor-logger.yaml:/root/sensor-logger.yaml
      - ./dripline_mesh.yaml:/root/.dripline_mesh.yaml
    environment:
      - DRIPLINE_USER=dripline
      - DRIPLINE_PASSWORD=dripline
    command:
      bash -c "dl-serve -vv -c /root/sensor-logger.yaml"
    networks:
      - mesh

  hbmon:
    image: ghcr.io/driplineorg/dripline-python:hbmon
    depends_on:
      - rabbit-broker
    volumes:
      - ./services/heartbeat-monitor.yaml:/root/heartbeat-monitor.yaml
      - ./dripline_mesh.yaml:/root/.dripline_mesh.yaml
    environment:
      - DRIPLINE_USER=dripline
      - DRIPLINE_PASSWORD=dripline
    command:
      bash -c "dl-serve -c /root/heartbeat-monitor.yaml"
    networks:
      - mesh

networks:
  mesh:
    external: TRUE
